"use client";

import { useCallback, useState, useRef, useEffect } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Tooltip,
  TooltipTrigger,
  TooltipContent,
} from "@/components/ui/tooltip";
import { Calculator, Pencil, PencilLine, Trash2 } from "lucide-react";
import { cn } from "@/lib/utils";
import {
  SortableList,
  type SortableItemProps,
} from "@/components/ui/sortable-list";
import { DragHandle } from "@/components/ui/drag-handle";

/** Identifies which cell is currently being edited inline. */
interface EditingCell {
  regelId: string;
  field: "omschrijving" | "hoeveelheid" | "prijsPerEenheid";
}

/** Ordered list of editable fields for Tab navigation. */
const EDITABLE_FIELDS: EditingCell["field"][] = [
  "omschrijving",
  "hoeveelheid",
  "prijsPerEenheid",
];

/**
 * Known scopes that are auto-generated by the offerte calculator.
 * Any regel with a scope NOT in this set is considered manually added.
 */
const AUTO_CALCULATED_SCOPES = new Set([
  "grondwerk",
  "bestrating",
  "borders",
  "houtwerk",
  "gras",
  "water_elektra",
  "specials",
  "schuttingen",
  "waterpartijen",
  "verlichting",
  "heggen",
  "bomen",
  "gras_onderhoud",
  "borders_onderhoud",
]);

interface Regel {
  id: string;
  scope: string;
  omschrijving: string;
  eenheid: string;
  hoeveelheid: number;
  prijsPerEenheid: number;
  totaal: number;
  type: "materiaal" | "arbeid" | "machine";
  margePercentage?: number;
  /** Explicitly marks a regel as manually added. When undefined, determined by scope. */
  handmatig?: boolean;
}

/**
 * Determines whether a regel is manually added (vs auto-calculated from scope).
 * Uses the explicit `handmatig` flag if present, otherwise falls back to
 * checking if the scope is in the known auto-calculated scopes set.
 */
function isHandmatigRegel(regel: Regel): boolean {
  if (regel.handmatig !== undefined) return regel.handmatig;
  return !AUTO_CALCULATED_SCOPES.has(regel.scope);
}

interface SortableRegelsTableProps {
  regels: Regel[];
  onReorder: (newRegels: Regel[]) => void;
  onEdit: (regel: Regel) => void;
  onDelete: (regelId: string) => void;
  scopeLabels: Record<string, string>;
  formatCurrency: (amount: number) => string;
  disabled?: boolean;
  /** Callback voor inline bewerking van een veld. Wordt aangeroepen bij bevestiging van de wijziging. */
  onRegelUpdate?: (regelId: string, field: string, value: string | number) => void;
}

interface SortableRegelRowProps {
  regel: Regel;
  sortableProps: SortableItemProps;
  onEdit: (regel: Regel) => void;
  onDelete: (regelId: string) => void;
  scopeLabels: Record<string, string>;
  formatCurrency: (amount: number) => string;
  instellingenMargePercentage?: number;
  editingCell: EditingCell | null;
  onEditingCellChange: (cell: EditingCell | null) => void;
  onRegelUpdate?: (regelId: string, field: string, value: string | number) => void;
}

/**
 * Inline editable cell component.
 * Dubbelklik om te bewerken. Enter bevestigt, Escape annuleert, Tab gaat naar het volgende veld.
 */
function InlineEditableCell({
  regelId,
  field,
  value,
  displayValue,
  isEditing,
  onStartEdit,
  onConfirm,
  onCancel,
  onTab,
  type = "text",
  className,
  children,
}: {
  regelId: string;
  field: EditingCell["field"];
  value: string | number;
  displayValue?: React.ReactNode;
  isEditing: boolean;
  onStartEdit: () => void;
  onConfirm: (value: string | number) => void;
  onCancel: () => void;
  onTab: (shiftKey: boolean) => void;
  type?: "text" | "number";
  className?: string;
  children?: React.ReactNode;
}) {
  const inputRef = useRef<HTMLInputElement>(null);
  const [editValue, setEditValue] = useState<string>(String(value));

  // Sync edit value and auto-focus when entering edit mode
  useEffect(() => {
    if (isEditing) {
      setEditValue(String(value));
      // Use requestAnimationFrame to ensure the input is rendered before focusing
      requestAnimationFrame(() => {
        inputRef.current?.focus();
        inputRef.current?.select();
      });
    }
  }, [isEditing, value]);

  const handleConfirm = useCallback(() => {
    if (type === "number") {
      const numValue = parseFloat(editValue);
      if (!isNaN(numValue) && numValue >= 0) {
        onConfirm(numValue);
      } else {
        onCancel();
      }
    } else {
      const trimmed = editValue.trim();
      if (trimmed) {
        onConfirm(trimmed);
      } else {
        onCancel();
      }
    }
  }, [editValue, type, onConfirm, onCancel]);

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent<HTMLInputElement>) => {
      if (e.key === "Enter") {
        e.preventDefault();
        handleConfirm();
      } else if (e.key === "Escape") {
        e.preventDefault();
        onCancel();
      } else if (e.key === "Tab") {
        e.preventDefault();
        handleConfirm();
        onTab(e.shiftKey);
      }
    },
    [handleConfirm, onCancel, onTab]
  );

  if (isEditing) {
    return (
      <Input
        ref={inputRef}
        type={type}
        value={editValue}
        onChange={(e) => setEditValue(e.target.value)}
        onBlur={handleConfirm}
        onKeyDown={handleKeyDown}
        className={cn(
          "h-8 text-sm",
          type === "number" && "text-right",
          className
        )}
        step={type === "number" ? "0.01" : undefined}
        min={type === "number" ? "0" : undefined}
        aria-label={`Bewerk ${field}`}
      />
    );
  }

  return (
    <div
      onDoubleClick={onStartEdit}
      className={cn(
        "cursor-default rounded-sm px-1 -mx-1 py-0.5 transition-colors",
        "hover:bg-accent/50 hover:ring-1 hover:ring-accent",
        className
      )}
      title="Dubbelklik om te bewerken"
    >
      {children ?? displayValue ?? value}
    </div>
  );
}

function SortableRegelRow({
  regel,
  sortableProps,
  onEdit,
  onDelete,
  scopeLabels,
  formatCurrency,
  instellingenMargePercentage,
  editingCell,
  onEditingCellChange,
  onRegelUpdate,
}: SortableRegelRowProps) {
  const handmatig = isHandmatigRegel(regel);

  const isEditingField = (field: EditingCell["field"]) =>
    editingCell?.regelId === regel.id && editingCell?.field === field;

  const startEdit = (field: EditingCell["field"]) => {
    onEditingCellChange({ regelId: regel.id, field });
  };

  const cancelEdit = () => {
    onEditingCellChange(null);
  };

  const confirmEdit = (field: EditingCell["field"], value: string | number) => {
    onEditingCellChange(null);
    if (onRegelUpdate) {
      onRegelUpdate(regel.id, field, value);
    }
  };

  const handleTab = (field: EditingCell["field"], shiftKey: boolean) => {
    const currentIndex = EDITABLE_FIELDS.indexOf(field);
    const nextIndex = shiftKey ? currentIndex - 1 : currentIndex + 1;
    if (nextIndex >= 0 && nextIndex < EDITABLE_FIELDS.length) {
      onEditingCellChange({ regelId: regel.id, field: EDITABLE_FIELDS[nextIndex] });
    } else {
      onEditingCellChange(null);
    }
  };

  return (
    <TableRow
      ref={sortableProps.setNodeRef}
      style={sortableProps.style}
      className={cn(
        "transition-colors",
        sortableProps.isDragging && "bg-accent/50",
        sortableProps.isOver && "bg-accent/30",
        handmatig && "border-l-2 border-l-amber-400"
      )}
    >
      <TableCell className="w-12">
        <DragHandle
          listeners={sortableProps.listeners}
          attributes={sortableProps.attributes}
          isDragging={sortableProps.isDragging}
          aria-label={`Versleep ${regel.omschrijving} om te herschikken`}
        />
      </TableCell>
      <TableCell>
        <div>
          <div className="flex items-center gap-1.5">
            <InlineEditableCell
              regelId={regel.id}
              field="omschrijving"
              value={regel.omschrijving}
              isEditing={isEditingField("omschrijving")}
              onStartEdit={() => startEdit("omschrijving")}
              onConfirm={(val) => confirmEdit("omschrijving", val)}
              onCancel={cancelEdit}
              onTab={(shiftKey) => handleTab("omschrijving", shiftKey)}
              className="font-medium"
            />
            <Tooltip>
              <TooltipTrigger asChild>
                <span className="inline-flex items-center text-muted-foreground/60 cursor-help">
                  {handmatig ? (
                    <PencilLine className="h-3.5 w-3.5" />
                  ) : (
                    <Calculator className="h-3.5 w-3.5" />
                  )}
                </span>
              </TooltipTrigger>
              <TooltipContent>
                {handmatig
                  ? "Handmatig toegevoegd"
                  : "Automatisch berekend vanuit scope"}
              </TooltipContent>
            </Tooltip>
          </div>
          <div className="flex items-center gap-1.5 text-sm text-muted-foreground">
            <span className="capitalize">{regel.type}</span>
            {regel.margePercentage !== undefined && (
              <Badge variant="secondary" className="text-[10px] px-1 py-0">
                {regel.margePercentage}% marge
              </Badge>
            )}
          </div>
        </div>
      </TableCell>
      <TableCell>
        <Badge variant="outline">{scopeLabels[regel.scope] || regel.scope}</Badge>
      </TableCell>
      <TableCell className="text-right">
        <div className="flex items-center justify-end gap-1">
          <InlineEditableCell
            regelId={regel.id}
            field="hoeveelheid"
            value={regel.hoeveelheid}
            isEditing={isEditingField("hoeveelheid")}
            onStartEdit={() => startEdit("hoeveelheid")}
            onConfirm={(val) => confirmEdit("hoeveelheid", val)}
            onCancel={cancelEdit}
            onTab={(shiftKey) => handleTab("hoeveelheid", shiftKey)}
            type="number"
            displayValue={regel.hoeveelheid}
          />
          <span className="text-muted-foreground">{regel.eenheid}</span>
        </div>
      </TableCell>
      <TableCell className="text-right">
        <InlineEditableCell
          regelId={regel.id}
          field="prijsPerEenheid"
          value={regel.prijsPerEenheid}
          isEditing={isEditingField("prijsPerEenheid")}
          onStartEdit={() => startEdit("prijsPerEenheid")}
          onConfirm={(val) => confirmEdit("prijsPerEenheid", val)}
          onCancel={cancelEdit}
          onTab={(shiftKey) => handleTab("prijsPerEenheid", shiftKey)}
          type="number"
          displayValue={formatCurrency(regel.prijsPerEenheid)}
        />
      </TableCell>
      <TableCell className="text-right font-medium">{formatCurrency(regel.totaal)}</TableCell>
      <TableCell>
        <div className="flex gap-1">
          <Button
            variant="ghost"
            size="icon"
            className="h-9 w-9 sm:h-8 sm:w-8"
            onClick={() => onEdit(regel)}
            aria-label="Bewerken"
          >
            <Pencil className="h-4 w-4" />
          </Button>
          <Button
            variant="ghost"
            size="icon"
            className="h-9 w-9 sm:h-8 sm:w-8"
            onClick={() => onDelete(regel.id)}
            aria-label="Verwijderen"
          >
            <Trash2 className="h-4 w-4 text-destructive" />
          </Button>
        </div>
      </TableCell>
    </TableRow>
  );
}

/**
 * A sortable table for offerte regels (line items).
 * Supports drag and drop reordering with accessibility features.
 */
export function SortableRegelsTable({
  regels,
  onReorder,
  onEdit,
  onDelete,
  scopeLabels,
  formatCurrency,
  disabled = false,
  onRegelUpdate,
}: SortableRegelsTableProps) {
  const [editingCell, setEditingCell] = useState<EditingCell | null>(null);

  const handleReorder = useCallback(
    (newItems: Array<{ id: string | number }>) => {
      // Rebuild the regels array in the new order
      const newRegels = newItems.map((item) => {
        const regel = regels.find((r) => r.id === item.id);
        return regel!;
      }).filter(Boolean);
      onReorder(newRegels);
    },
    [regels, onReorder]
  );

  // Add id field to regels for sortable list
  const sortableItems = regels.map((regel) => ({
    ...regel,
    id: regel.id,
  }));

  if (regels.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-8 text-center">
        <p className="text-muted-foreground">
          Nog geen regels. Klik op &quot;Regel toevoegen&quot; om te beginnen.
        </p>
      </div>
    );
  }

  return (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead className="w-12" aria-label="Drag handle"></TableHead>
          <TableHead>Omschrijving</TableHead>
          <TableHead>Scope</TableHead>
          <TableHead className="text-right">Hoeveelheid</TableHead>
          <TableHead className="text-right">Prijs</TableHead>
          <TableHead className="text-right">Totaal</TableHead>
          <TableHead className="w-[80px]"></TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        <SortableList
          items={sortableItems}
          onReorder={handleReorder}
          disabled={disabled}
          aria-label="Offerteregels"
          itemIdPrefix="regel"
          inline={true}
          renderItem={(item, sortableProps) => (
            <SortableRegelRow
              key={item.id}
              regel={item as Regel}
              sortableProps={sortableProps}
              onEdit={onEdit}
              onDelete={onDelete}
              scopeLabels={scopeLabels}
              formatCurrency={formatCurrency}
              editingCell={editingCell}
              onEditingCellChange={setEditingCell}
              onRegelUpdate={onRegelUpdate}
            />
          )}
        />
      </TableBody>
    </Table>
  );
}
